### ISSUE TITLE
...

### ISSUE THREAD

**Issue by ghost** [itsfuad/Telegram-Form-Bot#2]
Hey I'm working on a form project so i need to know how can i make the user to send a image file? please help me.

 > ``<input type="file">``

like using this :(

**Comment by itsfuad** [comment]
Working on client side is not a very well convenient way. Your credentials can be stolen and misused. That video was just an example that we can do this. That's is. To send file to the bot you need to use python server.

**Comment by ghost** [comment]
Ok, thanks for your information
